name = "news"
main = "src/index.js"
compatibility_date = "2023-10-16"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "310soft"
database_id = "72de8f6d-aac7-4097-a4c6-94ea99c44648"

[[kv_namespaces]]
binding = "allowed"   
id = "dfd99f12fcb040ee991e21c70a47214d"

[[services]]
binding = "auth"
service = "auth"

