name = "news"
main = "src/index.js"
compatibility_date = "2023-10-16"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "310soft"
database_id = "72de8f6d-aac7-4097-a4c6-94ea99c44648"

[[kv_namespaces]]
binding = "cache" 
id = "b0a46f83cead4ab7984f4c3dadf8f6ee"